app/models.py
from typing import List, TypedDict


class SteamUser(TypedDict):
    nick: str
    steam_id: int


class CompetitiveInfo(TypedDict):
    members: List[SteamUser]
    maps: List[str]


class User:
    def __init__(self, username, password):
        self.username = username
        self.password = password

app/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_cors import CORS

from .auth import auth
from .auth.flask_user import FlaskUser
from .stats import stats
from .competitives import competitive
from .provisional_test import test
from .stats.services import update_general_stats_data
from .competitives.services import update_players_and_maps_found_in_competitives
from .config import Config
from .db import db
from .scheduler import scheduler


login_manager = LoginManager()
login_manager.login_view = "auth.login"


@login_manager.user_loader
def load_user(username):
    return FlaskUser.get(username)


def create_app():

    # flask
    app = Flask(__name__)
    app.config.from_object(Config())
    login_manager.init_app(app)
    app.register_blueprint(auth)
    app.register_blueprint(stats)
    app.register_blueprint(competitive)
    app.register_blueprint(test)  # TODO delete this. Provisional.
    CORS(
        app,
        resources={r"/competitive/upload": {"origins": ["https://steamcommunity.com"]}},
    )
    print("▶ Flask app created and configured")

    # db
    db.init(app.config["MONGO_URI"])
    print("▶ DB initialized")

    # task scheduler
    scheduler.new_job(update_general_stats_data, app, hours=24)
    scheduler.new_job(update_players_and_maps_found_in_competitives, hours=24)

    scheduler.start()
    print("▶ Scheduler running. Tasks... ▼")
    scheduler.print_jobs()

    if app.config["UPDATE_ON_LAUNCH"]:
        print("▶ Update on launch activated. Running the scheduled tasks...")
        scheduler.run_jobs()

    return app

app/competitives/__init__.py
from flask import Blueprint

competitive = Blueprint("competitive", __name__, url_prefix="/competitive")

from . import views

app/competitives/views.py
from flask import render_template, request, current_app, jsonify
from flask_login import login_required
from bson import json_util
import json
from typing import List, Dict


from . import competitive
from .responses import error, success
from ..db import db, DBException


@competitive.route("/", methods=["GET"])
def index():
    partidas = db.get_all_competitive_matches()
    total_partidas = len(partidas)

    info = db.get_players_in_competitive()

    context = {
        "total_partidas": total_partidas,
        "partidas": json_util.dumps(partidas),
        "players": info["players"],
        "players_jsondump": json_util.dumps(info["players"]),
        "maps": info["maps"],
    }

    return render_template("competitive.html", **context)


@competitive.route("/match")
@login_required
def get_raw_competitives_matches():
    matches = db.get_all_competitive_matches()
    return jsonify(matches)


@competitive.route("/help_upload")
def help_subir_matches():
    return render_template("subir_matches.html")


@competitive.route("/upload", methods=["POST"])
def upload_games():
    try:
        if request.args["password"] == current_app.config["UPLOAD_PASS"]:
            # inserta base datos
            data = json.loads(request.data)

            matches: List[Dict] = data["matches"]
            for match in matches:
                match["_id"] = match.pop("datetime")

            try:
                n_inserted = db.insert_competitive_matches(matches)
                data = {"inserted": n_inserted, "total": len(matches)}
                return success(data=data, status_code=200)

            except DBException:
                return error("Insertion failed.", status_code=200)

        else:
            return error("pass not OK", status_code=200)

    except Exception as e:
        print(str(e))
        return error("Shit happend.", 400)

app/provisional_test/__init__.py
from flask import Blueprint

test = Blueprint("test", __name__, url_prefix="/test")

from . import views

app/provisional_test/views.py
"""Provisional file for testing stuff.

TODO erase this and create proper tests."""

from bson import json_util
from flask import Response, request, jsonify
import json

from . import test
from ..db import db


@test.route("/get")
def get_test():
    return Response(json_util.dumps({"result": "Ok"}), mimetype="application/json")


@test.route("/post", methods=["POST"])
def post_test():
    return Response(
        json_util.dumps(
            {"result": "Ok", "echo": request.json, "mimetype": request.mimetype}
        ),
        mimetype="application/json",
    )


@test.route("/db")
def insert_dummy():
    res = db._test()
    return Response(json_util.dumps(res.raw_result), mimetype="application/json")


@test.route("/jsonify")
def nify():
    res = jsonify({"result": "error", "description": "dummy."})
    print(res.response)
    return res


@test.route("/jsondump")
def dump():
    res = Response(
        response=json.dumps({"result": "error", "description": "dummy."}),
        status=200,
        mimetype="application/json",
    )
    print(res.response)
    return res

app/stats/__init__.py
from flask import Blueprint

stats = Blueprint("stats", __name__, url_prefix="/stats")

from . import views

app/stats/views.py
from bson import json_util
from flask import render_template, Response

from . import stats
from ..db import db


@stats.route("/", methods=["GET"])
def index():
    players = db.get_general_stats()
    names = sorted([member["nick"] for member in players], key=lambda s: s.lower())

    context = {"all_players": players, "names": names}

    return render_template("stats.html", **context)


@stats.route("/<member_id>", methods=["GET"])
def raw(member_id):
    result = db.get_player_public_stats(member_id)
    print("result", type(result))
    print("jsoned", type(json_util.dumps(result)))
    return Response(json_util.dumps(result), mimetype="application/json")

app/templates/admin.html
{% extends 'base.html' %}
{% block heading %}
{{ super() }}
<title>Admin</title>
{% endblock %}

{% block content %}
    <div class="container">
        This is aDmin
    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% block heading %}{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include 'imports.html' %}
</head>
<body>

{% include 'navbar.html' %}

{% for message in get_flashed_messages() %}
<div class="row">
  <div class="col-md-4 offset-md-4">
    <div class="alert alert-success alert-dismissible">
      <button type="button"
              data-dismiss="alert"
              class="close">&times;</button>
      {{ message }}
    </div>
  </div>
</div>
{% endfor %}

{% block content %}{% endblock %}

<script type="text/javascript" charset="utf8" src="{{url_for('static', filename='vue-logic.js')}}"></script>

</body>
</html>

app/templates/imports.html
<!-- <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" media="screen"> -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" media="screen">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<link type="text/css" rel="stylesheet" href="../static/styles.css">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script type="text/javascript" charset="utf8" src="{{url_for('static', filename='script.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

<!--<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/plug-ins/preview/searchPane/dataTables.searchPane.min.css">-->
<!--<script type="text/javascript" src="https://cdn.datatables.net/plug-ins/preview/searchPane/dataTables.searchPane.min.js"></script>-->

app/templates/login.html
{% extends 'base.html' %}
{% block heading %}
{{ super() }}
<title>Login</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col col-md-4 offset-md-4">
            <form method="POST" action="{{ url_for('auth.login') }}">
                <div class="row">
                    <div class="col">
                        <h3 class="text-center">Login</h3>
                        {{ login_form.csrf_token }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-2">
                        <label for="username">User:</label>
                    </div>
                    <div class="col-auto">
                        {{ login_form.username }} 
                    </div>
                </div>
                <div class="row">
                    <div class="col-2">
                        <label for="password">Pass:</label>
                    </div>
                    <div class="col-auto">
                        {{ login_form.password }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-8 text-center">
                        <input type="submit" class="btn btn-dark text-center btn-lg" value="Log In">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">CSGO Stats: Dofitos Bastardos!</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-csgo" aria-controls="navbar-csgo" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbar-csgo">
    <ul class="nav navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item"><a class="nav-link" href="{{ url_for('stats.index') }}">Public Stats</a></li>
      <li class="nav-item"><a class="nav-link" href="{{ url_for('competitive.index') }}">Competitives</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if current_user.is_authenticated %}
      <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Log Out</a></li>
      {% else %}
      <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.login') }}">Log In</a></li>
      {% endif %}
      <li class="nav-item"><a class="nav-link" href="http://apps.uborzz.es" target="_blank">Wow flask Apps</a></li>
      <li class="nav-item"><a class="nav-link" href="http://uborzz.es" target="_blank">blog: la caja loca</a></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/templates/stats.html
{% extends "base.html" %}

{% block heading %}
<title>CSGO Stats: General</title>
{% endblock %}

{% block content %}

<script type="text/javascript">
    document.all_members = {{ names | tojson }}
</script>
<div class="container">
    <h1>CSGO Stats: General - Dofitos Bastardos</h1>
    <p>Aquí se muestran algunas stats sacadas de la api de steam. Funciona con los miembros del grupo de steam Dofitos Bastardos.</p>
    <p>El perfil ha de tener públicos los Game Details para poder leer estas estadísticas. <a href="https://support.steampowered.com/kb_article.php?ref=4113-YUDH-6401" target="_blank">¿Cómo hacer el perfil público?</a> Quedando la configuración de <a href="../static/images/privacy-settings.png" target="_blank">ésta forma</a>.</p>
    <br>
    <h4 class="text-center">Panel principal: Stats</h4>
    <div class="row">
        <div class="col-sm-10">
            <table class="table table-striped" id="principal">
                <thead>
                    <tr>
                        <th class="text-center">Nick</th>
                        <th class="text-center">KD Ratio</th>
                        <th class="text-center">Rounds Won (%)</th>
                        <th class="text-center">Headshots (%)</th>
                        <th class="text-center">Accuracy (%)</th>
                        <th class="text-center">Time played (h)</th>
                        <th style="display:none">Steam ID</th>
                    </tr>
                </thead>
                <tbody>
                    {% for member in all_players %}
                    <tr onclick="location='/stats/{{member.steam_id}}'">
                        <td class="text-center">{{member['nick']}}</td>
                        <td class="text-center">{{member['kd_ratio']}}</td>
                        <td class="text-center">{{member['rounds_won']}}</td>
                        <td class="text-center">{{member['headshots']}}</td>
                        <td class="text-center">{{member['accuracy']}}</td>
                        <td class="text-center">{{member['time_played']}}</td>
                        <td style="display:none">{{member['steam_id']}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-sm-2">
            <input type="text" id="cont" value="" hidden>
            <div id="boxes">
                {% for member in names %}
                <div class="checkbox">
                    <label style="font-size: 1em">
                        <input name="names" type="checkbox" value="{{member}}" checked>
                        <span class="cr"><i class="cr-icon fa fa-check"></i></span>
                        {{member}}
                    </label>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/subir_matches.html
{% extends "base.html" %}

{% block heading %}
    <title>CSGO Stats: Subir partidas</title>
{% endblock %}

{% block content %}
<div class="container">
    <h1>CSGO Stats: Cómo subir partidas</h1>
    <h3> Enviar partidas - Instrucciones para subnormales. </h3>
    <p> Tras haber descargado y activado <a href="https://chrome.google.com/webstore/detail/csgo-competitive-matchine/nfjabioikcikngoihhfenimoapadlikd" target="_blank">el plugin de Chrome</a>...</p>
    <p> Acceder a la <a href="https://steamcommunity.com/" target="_blank">web de Steam</a> y Logear </p>
    <p> Ir a tu perfil, clickando por ejemplo en tu portrait y seleccionar Games del panel derecho.</p>
    <img class="seguida" src="../static/images/gpd-1.png" alt="Instrucciones 1">
    <p> Desplegar la personal game data en el item de Counter Strike: Global Offensive.</p>
    <img class="seguida" src="../static/images/gpd-2.png" alt="Instrucciones 2">
    <p> Ir a la pestaña Competitive. Si habéis instalado bien mi plugin, aparecerán unos botones extra.</p> 
    <p><b>OJO!</b> La dirección de envío actual es la siguiente: <b>https://csgo.uborzz.es/competitive/upload</b></p>
    <img class="seguida" src="../static/images/gpd-3.png" alt="Instrucciones 3">
    <p>Una vez en la pestaña con la información de las competitivas, el modo de uso sería:</p>
    <ul>
    <li>Clickar en el primer botón (Load whole match history) hasta cargar todas las partidas. Si se quiere parar antes, dar al segundo botón (Stop scanning).</li>
    <li>Asegurarse de que el endpoint y la pass son correctos. Endpoint: https://csgo.uborzz.es/competitive/upload. Nuestra password la tendréis en el telegram.</li>
    <li>Por último, pulsar el tercer botón (Send to endpoint).</li>
    </ul>
    <p> El contenido subido se vera actualizado en unos instantes en <a href="/competitive" target="_blank">la pestaña competitive</a>.</p>
<br>
</div>
{% endblock %}